### ISSUE TITLE
Consulta técnica

### ISSUE THREAD

**Issue by fmigliavacca** [pdepjm/2024-tp0-presentacion-GonGarciaFontenla#1]
Hola Gonza! Veo que pones que sos un apasionado por la programación y todas las cuestiones tech. Teniendo en cuenta eso, si un familiar mayor ejemplo abuelo/a te preguntara: "Gonza querido, ¿Vos me podrías instalar el soporte de la televisión a la pared?". Te considerás capacitado para realizar tal labor, o lo delegarías a un técnico especializado?. Justifica tu respuesta porfavor. Saludos crack!

**Comment by GonGarciaFontenla** [comment]
Holaaa, muy interesante la pregunta! Considero que si podría instalar el soporte, pero no tanto por mis conocimientos en la programación, sino mas bien porque siempre me he dado mucha maña para ese tipo de cosas.
