### ISSUE TITLE
¡Mucho gusto Gonza! algunas sugerencias:

### ISSUE THREAD

**Issue by EzequielSecchi** [pdepjm/2024-tp0-presentacion-GonGarciaFontenla#3]
¡Hola Gonzalo! mucho gusto, y espero que puedas mejorar en cada una de tus pasiones

Te doy una sugerencia que, al menos a mi, me sirvieron. Si es que estas interesado en mejorar tu descripción puedes utilizar la Sintaxis de "MarkDown", para poder darle a tu presentación mucho mas estilo

por ejemplo, usar los "*" para curvar tu texto o hacer las famosas "Letras negritas".
Algo así: **Letras negritas**, o *Letras curvas* 

desde ya te mando un saludo y espero que podamos tener una muy buena cursada

**Comment by GonGarciaFontenla** [comment]
Muchas gracias por el aporte, lo voy a tener en cuenta!
